#-------------------------------
# General Site Settings

title: Oran Gerbovski
email: tnbuig@gmail.com
description: "Programmer // Traveler // Human"

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Travel, url: '#travel'}
- {name: Projects, url: '#projects'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.
seo:
  description: 'Oran Gerbovski Blog Devloper C#'
  rel-author: 'https://plus.google.com/+tnbuig/'
  rel-publisher: 'https://plus.google.com/+tnbuig'


#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **In each and every one of us there is a small artist** and the artist want to creat new things 
  and have his/her say in this world.
  Welcome to my two cents in this small corner of the web.
  
  A C# developer whos interest in *New* or *different*, that also why i like traveling
  and getting to experience different cultures and new places.
  So what better then having a site to present some ideas in a semi private stage.

  This site design and inspiration credits go to "youtube.com/user/DevTipsForDesigners".
  Comments and suggestion are welcome.

  Thanks for visiting.



skills:
- {name: Team Work, value: '8'}
- {name: Organization, value: '6'}
- {name: Learning, value: '6'}
- {name: Curiosity, value: '8'}
- {name: Planning, value: '7'}
- {name: Refactoring, value: '5'}
- {name: Adaptability, value: '7'}
- {name: Programming, value: '6'}

#-------------------------------
# Travel Section

trips:
- {name: Israel, folder: 'trip-1', file: 'travel/trip-1.html'}
- {name: Netherlands, folder: 'trip-2', file: 'travel/trip-2.html'}
- {name: Bulgaria, folder: 'trip-3', file: 'travel/trip-3.html'}
- {name: Germany, folder: 'trip-4', file: 'travel/trip-4.html'}
- {name: Slovakia, folder: 'trip-5', file: 'travel/trip-5.html'}
- {name: Timeline Page, folder: 'trip-6', file: 'travel/trip-6.html'}
- {name: U.S.A, folder: 'trip-7', file: 'travel/trip-7.html'}
- {name: Mongolia, folder: 'trip-8', file: 'travel/trip-8.html'}




#-------------------------------
# Projects Section

projects:
- {avatar: 'Twitter-api-Mvvm.jpg',
  name: 'Twitter Api MVVM WPF',
  title: 'Tutorial to Consum Web Api from WPF Based Client',
  quote: '<p><strong>Wanne Follow random twits from finland</strong> Isnt that crazy useless idea? Well now you have the code to support it and well desinged as well, good tutorial for learning how to consume Web Api From WPF client according to MVVM desing pattern</p>',
  logo: 'logo3.png'}
- {avatar: 'Planning-Poker.jpg',
  name: 'Complete and Basic Website',
  title: 'Tutorial to create a free online(not local) website with using only Html Css and Php',
  quote: '<p><strong>Learned to run before you can walk?</strong>Ignoring the hundreths of free Libraries&Frameworks available will leave you behhind and in the dark, so this tutorial will help you to get the building blocks of website development by doing.</p>',
  logo: 'logo4.png'}
   
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'facebook', link: 'http://facebook.com'}
- {icon: 'github', link: 'https://github.com/tnbuig'}
- {icon: 'couchsurfing', link: 'https://www.couchsurfing.com/users/1559177/profile'}
- {icon: 'youtube', link: 'https://www.youtube.com/user/tnbuig'}
- {icon: 'linkedin', link: 'de.linkedin.com/in/OranGerbovsk'}

  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  